const express=require("express"),path=require("path"),crypto=require("crypto"),Database=require("better-sqlite3");
const app=express(),PORT=process.env.PORT||3000;
const ADMIN_USER=process.env.ADMIN_USER||"admin",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"CHANGE_ME_NOW",WA=process.env.WA_NUMBER||"2348012345678";
const db=new Database(process.env.DB_FILE||"data.sqlite");
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,price INTEGER,description TEXT,icon TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,customer_name TEXT,phone TEXT,address TEXT,delivery TEXT,total INTEGER,status TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT,product_id INTEGER,name TEXT,qty INTEGER,price INTEGER);`);
if(db.prepare("SELECT COUNT(*) c FROM products").get().c===0){let q=db.prepare("INSERT INTO products(name,category,price,description,icon) VALUES(?,?,?,?,?)");[
["Dangote 3X Cement (50kg)","Cement",11500,"Quality cement for general construction.","🧱"],
["Block Master Cement (50kg)","Cement",11500,"Reliable cement for block making.","🧱"],
["60×60 Ceramic Tiles","Tiles",6850,"Modern ceramic tiles for floors and walls.","◻️"],
["12mm Iron Rod","Iron Rods",8300,"Strong reinforcement rod for construction.","〽️"]
].forEach(x=>q.run(...x))}
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
const sessions=new Set(),money=n=>"₦"+Number(n).toLocaleString("en-NG");
const auth=(req,res,next)=>{let t=req.headers.authorization?.replace("Bearer ","");if(!t||!sessions.has(t))return res.status(401).json({error:"Unauthorized"});next()};
app.get("/api/products",(req,res)=>{let q=(req.query.q||"").toLowerCase(),c=req.query.category||"All";res.json(db.prepare("SELECT * FROM products WHERE active=1 ORDER BY id DESC").all().filter(p=>(c==="All"||p.category===c)&&(!q||(p.name+" "+p.category+" "+p.description).toLowerCase().includes(q))))});
app.get("/api/categories",(req,res)=>res.json(db.prepare("SELECT DISTINCT category FROM products WHERE active=1 ORDER BY category").all().map(x=>x.category)));
app.post("/api/orders",(req,res)=>{let {customerName,phone,address,delivery,items}=req.body;if(!customerName||!phone||!address||!items?.length)return res.status(400).json({error:"Complete customer details and cart are required"});let total=0,rows=[];for(let i of items){let p=db.prepare("SELECT * FROM products WHERE id=? AND active=1").get(i.productId),qty=Math.max(1,Math.floor(Number(i.qty)||0));if(!p||!qty)return res.status(400).json({error:"Invalid product"});total+=p.price*qty;rows.push({p,qty})}let fee=delivery==="Express"?4000:2000;total+=fee,id="HSV-"+crypto.randomBytes(3).toString("hex").toUpperCase(),now=new Date().toISOString();let tx=db.transaction(()=>{db.prepare("INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?)").run(id,customerName,phone,address,delivery,total,"New",now);let s=db.prepare("INSERT INTO order_items(order_id,product_id,name,qty,price) VALUES(?,?,?,?,?)");rows.forEach(x=>s.run(id,x.p.id,x.p.name,x.qty,x.p.price))});tx();let itemsText=rows.map(x=>`${x.qty} × ${x.p.name} — ${money(x.p.price*x.qty)}`).join("\n");let text=encodeURIComponent(`Hello Hamid & Son's Ventures,\n\nOrder: ${id}\nCustomer: ${customerName}\nPhone: ${phone}\nAddress: ${address}\nDelivery: ${delivery}\n\n${itemsText}\nDelivery: ${money(fee)}\nTotal: ${money(total)}`);res.json({id,total,whatsapp:`https://wa.me/${WA}?text=${text}`})});
app.post("/api/admin/login",(req,res)=>{if(req.body.username===ADMIN_USER&&req.body.password===ADMIN_PASSWORD){let t=crypto.randomBytes(24).toString("hex");sessions.add(t);return res.json({token:t})}res.status(401).json({error:"Invalid login"})});
app.get("/api/admin/products",auth,(req,res)=>res.json(db.prepare("SELECT * FROM products ORDER BY id DESC").all()));
app.patch("/api/admin/products/:id",auth,(req,res)=>{let p=db.prepare("SELECT * FROM products WHERE id=?").get(req.params.id);if(!p)return res.status(404).json({error:"Not found"});let x={...p,...req.body};db.prepare("UPDATE products SET name=?,category=?,price=?,description=?,icon=?,active=? WHERE id=?").run(x.name,x.category,Number(x.price),x.description,x.icon,x.active?1:0,p.id);res.json(db.prepare("SELECT * FROM products WHERE id=?").get(p.id))});
app.post("/api/admin/products",auth,(req,res)=>{let {name,category,price,description="",icon="📦"}=req.body;if(!name||!category||!Number(price))return res.status(400).json({error:"Name, category and price required"});let r=db.prepare("INSERT INTO products(name,category,price,description,icon) VALUES(?,?,?,?,?)").run(name,category,Number(price),description,icon);res.json(db.prepare("SELECT * FROM products WHERE id=?").get(r.lastInsertRowid))});
app.delete("/api/admin/products/:id",auth,(req,res)=>{db.prepare("UPDATE products SET active=0 WHERE id=?").run(req.params.id);res.json({ok:true})});
app.get("/api/admin/orders",auth,(req,res)=>res.json(db.prepare("SELECT * FROM orders ORDER BY created_at DESC").all()));
app.patch("/api/admin/orders/:id",auth,(req,res)=>{let ok=["New","Confirmed","Preparing","Out for delivery","Delivered","Cancelled"];if(!ok.includes(req.body.status))return res.status(400).json({error:"Invalid status"});db.prepare("UPDATE orders SET status=? WHERE id=?").run(req.body.status,req.params.id);res.json({ok:true})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("Running on "+PORT));